name: Tests

on: [push, pull_request]

env:
  ARCHIVE_LINK: https://github.com/starkware-libs/cairo/releases/download/v2.0.2/release-x86_64-unknown-linux-musl.tar.gz
  ARCHIVE_NAME: cairo.zip

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "0.5.2"
      - run: scarb test